# Generated by Django 4.2.5 on 2023-11-04 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_housename', models.CharField(max_length=200)),
                ('user_roadname', models.CharField(max_length=200)),
                ('user_pincode', models.CharField(max_length=200)),
                ('user_state', models.CharField(max_length=200)),
                ('user_city', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_img', models.ImageField(upload_to='Categories')),
                ('category_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=200)),
                ('prd_name', models.CharField(max_length=200)),
                ('prd_img', models.ImageField(upload_to='Categories')),
                ('prd_rate', models.IntegerField()),
                ('prd_quantity', models.IntegerField()),
                ('prd_desc', models.CharField(max_length=500)),
                ('seller_company', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
                ('trackingid', models.CharField(max_length=200)),
                ('prd_rate', models.CharField(max_length=200)),
                ('prd_qty', models.CharField(max_length=200)),
                ('createdat', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
