# Generated by Django 4.2.5 on 2023-09-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_img', models.ImageField(upload_to='Categories')),
                ('category_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=200)),
                ('prd_name', models.CharField(max_length=200)),
                ('prd_img', models.ImageField(upload_to='Categories')),
                ('prd_rate', models.FloatField()),
                ('prd_quantity', models.IntegerField()),
                ('prd_desc', models.CharField(max_length=1000)),
                ('seller_company', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.categories')),
            ],
        ),
    ]
