# Generated by Django 4.2.5 on 2023-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prd_desc',
            field=models.CharField(max_length=500),
        ),
    ]
