# Generated by Django 4.2.5 on 2023-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_qty',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
