# Generated by Django 4.2.5 on 2023-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0006_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
