# Generated by Django 4.2.5 on 2023-09-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0007_cart_quantity_cart_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rate',
        ),
    ]
