# Generated by Django 4.2.5 on 2023-11-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0007_products_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
    ]
