# Generated by Django 4.2.5 on 2023-09-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopyfield_home', '0008_remove_cart_quantity_remove_cart_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('trackingid', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.address')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
