# Generated by Django 4.2.5 on 2023-09-12 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
