# Generated by Django 4.2.5 on 2024-01-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0009_main_categories_remove_cart_product_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_categories',
            name='cat_img',
            field=models.ImageField(default=1, upload_to='Categories'),
            preserve_default=False,
        ),
    ]
