# Generated by Django 4.2.5 on 2024-01-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0010_main_categories_cat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=200)),
                ('sub_cat_img', models.ImageField(upload_to='Categories')),
                ('sub_category_code', models.CharField(max_length=200)),
            ],
        ),
    ]
