# Generated by Django 4.2.5 on 2023-09-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0010_cart_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='createdat',
        ),
    ]
