# Generated by Django 4.2.5 on 2023-09-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0011_remove_cart_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products')),
            ],
        ),
    ]
