# Generated by Django 4.2.5 on 2024-01-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0011_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.main_categories'),
            preserve_default=False,
        ),
    ]
