# Generated by Django 4.2.5 on 2023-09-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0012_remove_orders_quantity_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
    ]
