# Generated by Django 4.2.5 on 2024-01-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0012_categories_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_cat_img',
        ),
    ]
