# Generated by Django 4.2.5 on 2023-09-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0014_orders_price_orders_product_orders_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='prd_qty',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='quantity',
            new_name='prd_rate',
        ),
    ]
