# Generated by Django 4.2.5 on 2024-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0014_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prd_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
