# Generated by Django 4.2.5 on 2023-09-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0015_rename_price_orders_prd_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='createdat',
            field=models.DateField(auto_now_add=True),
        ),
    ]
