# Generated by Django 4.2.5 on 2023-09-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0016_alter_orders_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='prd_qty',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='prd_rate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_rate', models.CharField(max_length=200)),
                ('prd_qty', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products')),
            ],
        ),
    ]
