# Generated by Django 4.2.5 on 2023-09-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0017_remove_orders_prd_qty_remove_orders_prd_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order',
            new_name='orders',
        ),
    ]
