# Generated by Django 4.2.5 on 2023-09-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopyfield_home', '0018_rename_order_orderitems_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prd_qty',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='prd_rate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopyfield_home.products'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Orderitems',
        ),
    ]
